// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteFile(arg1:string):Promise<void>;

export function FindDuplicates(arg1:string):Promise<Array<main.FileDetailsResult>>;

export function Greet(arg1:string):Promise<string>;

export function SelectDirectory():Promise<string>;
