// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteFiles(arg1:Array<string>):Promise<void>;

export function FindDuplicates(arg1:string):Promise<Array<main.FileDetailsResult>>;

export function SelectDirectory():Promise<string>;
