// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFiles(arg1) {
  return window['go']['main']['App']['DeleteFiles'](arg1);
}

export function FindDuplicates(arg1) {
  return window['go']['main']['App']['FindDuplicates'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
