// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function FindDuplicates(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindDuplicates'](arg1, arg2, arg3);
}

export function GetPage(arg1, arg2) {
  return window['go']['main']['App']['GetPage'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}
