name: Release

# Allow the workflow to save release artifacts
permissions:
  contents: write
  packages: write

on:
  push:
    tags:
      - '*'

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'dupesnoop'
            platform:  'linux/amd64'
            os: 'ubuntu-latest'
          - name: 'dupesnoop'
            platform:  'windows/amd64'
            os: 'windows-latest'
          - name: 'dupesnoop'
            platform:  'darwin/universal'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: true
          go-version: '1.22'
          node-version: '20'